### ISSUE TITLE
Cannot use Sort

### ISSUE THREAD

**Issue by maponzzi** [mailjet/mailjet-apiv3-python#46]
I'm trying get my campaigns ordering by CreatedAt field but I get an error message:
filters = { 'Sort': 'CreatedAt+DESC' }
campaigns = mailjet.campaign.get(filters=filters)
campaign.json()
{u'ErrorInfo': u'',
 u'ErrorMessage': u'Unexpected error during GET: Invalid sort specification: Cannot sort on field createdat+desc',
 u'StatusCode': 400}

any idea ?

**Comment by adamyanliev** [comment]
hi @maponzzi,

As mentioned in the API reference, depending on the API endpoint, the `Sort` filter allows ordering only based on certain properties, and does not always allow descending ordering. For the campaign endpoint you can use `Sort` only to order by `ID` in both descending and ascending order. That's why you're getting the above error.

FYI by default the campaigns are being retrieved based on `CreatedAt`, but in ascending order.

It's possible that we will include additional sort options in the future, but I cannot promise you anything at this point.

Regards,
Atanas

**Comment by maponzzi** [comment]
Ok,
I achieved get campaigns ordered by ID using python requests and this url: 
https://api.mailjet.com/v3/REST/campaign/?From=melissap@somosindustria.com&Sort=ID+DESC

but I can't order by ID+DESC using this mailjet python wrapper, 

I've tried:
filters = {'From': 'abc@mydomain.com', 'Sort': 'ID+DESC'}
filters = {'From': 'abc@mydomain.com', 'Sort': '-ID'}
filters = {'From': 'abc@mydomain.com', 'Sort': 'ID-'}
filters = {'From': 'abc@mydomain.com', 'Sort': 'ID-DESC'}

but I only get error message:
'Unexpected error during GET: Invalid sort specification: Cannot sort on field id-desc'

Do you know how can I set this ordering by ID Descending ?
