### ISSUE TITLE
How do you override the limit for get?

### ISSUE THREAD

**Issue by fpessolano** [mailjet/mailjet-apiv3-python#77]
How do you set the limit to more than 10 for getting contacts?

**Comment by shawmat** [comment]
How to do pagination is not clear to me either.  Using Limit and Offset are in the API documentation but no examples.  

I've raised a ticket and will post the answer here.

**Comment by shawmat** [comment]
Digging around in the test script (test.py) I found an answer which is otherwise undocumented.

Instead of:

result = mailjet.contact.get()

try...

result = mailjet.contact.get(filters={'limit': 0})

It appears to override the default response of 10 items.  I have not yet tested whether the upper limit of 1000 kicks in because I haven't loaded sufficient contacts yet.  Paging using filters={'limit': 0, offset: 1000}) should fetch the second 1000 if so.

**Comment by kmanchikov** [comment]
Hi There, 

The `limit` filter will indeed set the max number of objects in the response, if that is equals to "0" then it will respond back with the maximum number of object set on a system level which is 1000. As @shawmat said, if you would like to leverage more than those 1000 you would need to use an `offset` which will set the starting point of our output, and pull the next 1k.

**Comment by fpessolano** [comment]
Thanks. Will check it ASAP!

**Comment by DanyilNefodov** [comment]
Hi, I've introduced filtering doc at [1.3.5 release](https://github.com/mailjet/mailjet-apiv3-python/releases/tag/1.3.5)
